### GET All movies
GET http://localhost:1234/movies

### GET movie by id
GET http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
### GET movie by genre
GET http://localhost:1234/movies?genre=crime

### Create Movie with POST

POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "La leyenda de la Leyenda",
    "year": 1999,
    "director": "Javi",
    "duration": 130,
    "poster": "https://i.ebayimg.com/images/g/yokAAOSw8w1YARbm/s-l1200.jpg",
    "genre": [
        "Action",
        "Crime",
        "Drama",
        "Adventure"
    ]
}

### Actualizar una pelicula
PATCH http://localhost:1234/movies/f7224653-441e-4b41-932a-9de1a7d8c92a
Content-Type: application/json

{
    "title": "leyen edited"
}

###DELETE movie
DELETE http://localhost:1234/movies/f7224653-441e-4b41-932a-9de1a7d8c92a
